name: "ASD documents"

on:
  ["push", "workflow_dispatch"]

jobs:
  asd:
    runs-on: ubuntu-latest
    name: ASD documents
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generates ASD documents
        uses: koriym/asd-action@v1
        id: asd
        with:
          config: profile.xml

      - uses: actions/upload-artifact@v2
        with:
          name: ASD documents
          path: ./asd-public

